trigger:
  - master
pr:
  - master
pool:
  vmImage: ubuntu-16.04
steps:
  - task: DockerCompose@0
    inputs:
      action: Run a specific service
      additionalDockerComposeFiles: docker-compose.test.yml
      serviceName: web
      containerCommand: pytest
      arguments: --use-aliases
