version: '3'
services:
  web:
    build: ./backend
    command: ['gunicorn', '--reload', '--bind=0.0.0.0:8000', 'eahub.config.wsgi']
    depends_on:
      - assets
      - db
      - objstore
      - cache
      - mail
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - webpack-stats:/webpack-stats
    environment:
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY:
      LEGACY_DATABASE_URL:
      LOCAL_GROUPS_AIRTABLE_API_KEY:
      LOCAL_GROUPS_AIRTABLE_BASE_KEY:
      ADMINS: Local Admin=admin@example.com
      AZURE_CONNECTION_STRING: UseDevelopmentStorage=true;BlobEndpoint=objstore:8002
      AZURE_CONTAINER: media
      CACHE_URL: redis://cache
      DATABASE_URL: postgresql://postgres:development_db_password@db/postgres
      DEBUG: 'True'
      EMAIL_URL: smtp://mail:1025
      HOSTS: web,localhost
      HTTPS: 'False'
      LEAN_MANAGERS: Local Manager=leanmanager@example.com
      PYTHONDONTWRITEBYTECODE: 'True'
      RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      SECRET_KEY: development_secret_key
  assets:
    build: ./frontend
    image: eahub.org/assets
    ports:
      - 8003:8003
    volumes:
      - ./frontend:/frontend
      - webpack-stats:/webpack-stats
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: development_db_password
  objstore:
    image: arafato/azurite:2.6.5
    command: ['node', 'bin/blob', '--location=/opt/azurite/folder', '--blobPort=8002']
    ports:
      - 8002:8002
  cache:
    image: redis:3.2.7
  mail:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 8001:1080
volumes:
  webpack-stats:
