version: '3'
services:
  web:
    build: ./eahub/
    command: gunicorn --reload --bind=0.0.0.0:8000 eahub.config.wsgi
    depends_on:
      - db
      - objstore
      - cache
      - mail
      - webdriver
      - chrome
      #- firefox
    ports:
      - 8000:8000
      - 8003:8003
    volumes:
      - ./eahub/:/code/eahub/
    environment:
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY:
      LEGACY_DATABASE_URL:
      LOCAL_GROUPS_AIRTABLE_API_KEY:
      LOCAL_GROUPS_AIRTABLE_BASE_KEY:
      ADMINS: Local Admin=admin@example.com
      AZURE_CONNECTION_STRING: UseDevelopmentStorage=true;BlobEndpoint=objstore:8002
      AZURE_CONTAINER: media
      CACHE_URL: redis://cache:6379/0
      DATABASE_URL: postgresql://postgres:development_db_password@db:5432/postgres
      DEBUG: 'True'
      EMAIL_URL: smtp://mail:1025
      HOSTS: web,localhost
      HTTPS: 'False'
      LEAN_MANAGERS: Local Manager=leanmanager@example.com
      PYTHONDONTWRITEBYTECODE: 'True'
      RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      SECRET_KEY: development_secret_key
      TEST_SERVER_PORT: '8003'
      WEBDRIVER_BROWSERS: chrome #,firefox
      WEBDRIVER_URL: http://webdriver:4444/wd/hub
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: development_db_password
    ports:
      - 5432:5432
  objstore:
    image: arafato/azurite:2.6.5
    command: node bin/blob --location=/opt/azurite/folder/ --blobPort=8002
    ports:
      - 8002:8002
  cache:
    image: redis:3.2.7
  mail:
    image: dockage/mailcatcher:0.6.5
    ports:
      - 8001:1080
  webdriver:
    image: selenium/hub:3.141.59-iron
    environment:
      GRID_DEBUG: 'true'
  chrome:
    image: selenium/node-chrome-debug:3.141.59-iron
    depends_on:
      - webdriver
    ports:
      - 5900:5900
    environment:
      GRID_DEBUG: 'true'
      HUB_HOST: webdriver
      VNC_NO_PASSWORD: '1'
  firefox:
    image: selenium/node-firefox:3.141.59-iron
    depends_on:
      - webdriver
    environment:
      GRID_DEBUG: 'true'
      HUB_HOST: webdriver
